### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by furkankapici** [g4o2/PHP-SQL-Chat#9]
When i try to my console says:
POST http://localhost/login.php 500 (Internal Server Error)
Uncaught TypeError: Cannot read properties of null (reading 'getElementsByClassName')
    at window.particlesJS (particles.js:1495:30)
    at xhr.onreadystatechange (particles.js:1531:16)

**Comment by furkankapici** [comment]
@Maxhu787

**Comment by Maxhu787** [comment]
Fixed, git pull and try it again ;)
